### PR TITLE
Question loading

### LINKED ISSUE #3: Loading the questions
Load the `questions.yml` file into our `Question` model. Write a static method called `Question.load` with the file path as input and a list of question instances as output. 

For testing create a script called `test_load.py` and an example `questions.yml` in the `tests` folder.

I've found this stackOverflow thread, I hope it helps something. https://stackoverflow.com/questions/1773805/how-can-i-parse-a-yaml-file-in-python

Feel free to ask from me any time. Just leave a comment below this issue.

### PR DESCRIPTION
**Pull request by EndergamerHUN**
Question loading system.

### CODE REVIEW

**Comment by d0ty** [comment]
What libraries did you use for yaml parsing?

**Comment by EndergamerHUN** [comment]
I used pyyaml, you can get it with pip. I can make a step by step on how to do it in pycharm.

**Comment by d0ty** [comment]
[test_load_results.txt](https://github.com/Engame-Coding-Society/engame-quiz/files/13326338/test_load_results.txt)
Test results seem okay

**Review by d0ty — APPROVED** [review]
Cool stuff. Thanks for the nice PR.

**Pull request merged**
