### PR TITLE
Randomize the questions

### LINKED ISSUE #4: Randomize the questions
Create an array randomization algorythm into the `randomization.py` script. For testing, create a script called `test_random.py` into the `tests` folder. Write a simple test here with 10 random question instance (import it from `question.py` from the parent dir.

Feel free to ask from me any time. Just leave a comment below this issue.

### PR DESCRIPTION
**Pull request by yefetk**
i created a new branch because i managed to mess up the previous one.

### CODE REVIEW

**Comment by d0ty** [comment]
Cool. What about test results? Can you comment here the terminal result of your test?

And then I can merge in (tomorrow morning).

**Comment by yefetk** [comment]
Traceback (most recent call last):
  File "C:\Users\Yefet Koren\AppData\Local\Programs\Python\Python39\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_random
Traceback (most recent call last):
  File "C:\Users\Yefet Koren\AppData\Local\Programs\Python\Python39\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\Yefet Koren\Documents\GitHub\engame-quiz\tests\test_random.py", line 2, in <module>
    from question import Question
  File "C:\Users\Yefet Koren\Documents\GitHub\engame-quiz\question.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by d0ty** [comment]
Install pyyaml and it will be fine! Anyway nice unit test. Can you iterate over the random results to make sure they're random?
If you'd like I can do this.

**Comment by yefetk** [comment]
It would be great if you could do it as I won't be near my computer today.

**Comment by d0ty** [comment]
Test results:
Testing started at 17:32 ...
Question 5
Question 7
Question 9
Question 8
Question 1


Ran 1 test in 0.002s

OK
Question 4
Question 2
Question 3
Question 10
Question 6

Process finished with exit code 0

**Review by d0ty — APPROVED** [review]
Thanks for your work

**Pull request merged**
